name: Test
on:
  push:
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 10  # Increase this if it's too hurry.
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # be patient with everyone.
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - windows-2022
          - windows-2025
          - macos-26
          - macos-26-intel
    env:
      # Do not mess up anything in our workspace.
      IQTA_WORKING_DIR: '../iqta-action'
      # Change these two as per your need.
      REPOSITORY: 'jurplel/install-qt-action'
      REF: '5527a0292e62299031937ff8360329f5aa5cc6e6'
    steps:
      # "actions/checkout" does not allow us to clone into any places other than $GITHUB_WORKSPACE.
      - name: Checkout
        run: |
          git clone \
            --no-checkout \
            https://github.com/$REPOSITORY \
            $IQTA_WORKING_DIR
          git -C $IQTA_WORKING_DIR switch -d $REF
        shell: bash

      # "actions/setup-node" does not allow us to use relative paths for cache.
      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24

      - name: Build action
        run: |
          set -ex

          cd action
          npm ci
          npm run build
        shell: bash
        working-directory: "${{ env.IQTA_WORKING_DIR }}"

      # See the root "action.yml" file.
      - name: Use local built internal action (hack)
        run: |
          sed -i.bak "s|uses: \$/action|uses: $PWD/action|" action.yml
          diff -u action.yml.bak action.yml || true
          git status --porcelain
        shell: bash
        working-directory: "${{ env.IQTA_WORKING_DIR }}"

      - name: Install Qt
        uses: "./$IQTA_WORKING_DIR"
