name: Test
on:
  push:
  workflow_dispatch:
jobs:
  test:
    timeout-minutes: 10  # Increase this if it's too hurry.
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false  # be patient.
      matrix:
        os:
          - ubuntu-22.04
          - ubuntu-24.04
          - windows-2022
          - windows-2025
          - macos-26
          - macos-26-intel
    env:
      # Do not mess up anything in our workspace.
      IQTA_ACTION_WORKING_DIR: ../iqta-action
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          path: "$IQTA_ACTION_WORKING_DIR"
          # Change these two as per your need.
          repository: jurplel/install-qt-action
          ref: 5527a0292e62299031937ff8360329f5aa5cc6e6

      - uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
        with:
          node-version: 24
          cache: npm

      - name: Build action
        run: |
          set -ex

          cd action
          npm ci
          npm run build
        shell: bash
        working-directory: "$IQTA_ACTION_WORKING_DIR"

      # See the root "action.yml" file.
      - name: Use local built internal action (hack)
        run: |
          sed -i.bak 's|uses: $/action|uses: ./action|' action.yml
          diff -u action.yml.bak action.yml || true
          git status --porcelain
        shell: bash
        working-directory: "$IQTA_ACTION_WORKING_DIR"

      - name: Install Qt
        uses: "./$IQTA_ACTION_WORKING_DIR"
